# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46907f0f123b0259c7df22cb3e89680b48a6e31a92711008b48ee668006440c75093947f6e21000b683b155223b123dae26e8435014b765f3fe62609376f37d

test:
  secret_key_base: 99f4712f7c5dd9796770a08c2cad9839d0a616262b04510cfa3c93a483b342775de717db4233fa53f9de1a81a8899e5bd2eb738d9a2d9332e5aba6b15f9bdb51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
